[build]
  base = "src"  # Указывает Netlify, что исходный код находится в папке src
  publish = "build"  # Папка, куда будет собран проект и опубликован
  command = "npm run build"  # Команда для сборки проекта (если используешь npm или yarn)
