[build]
  base = "/opt/build/repo"
  command = "npm install && npm run build && npm run export"  # Стандартная сборка с экспортом
  publish = "out"  # Папка, куда Next.js экспортирует статические файлы
