[build]
  command = "npm run build"
  publish = "out"  # Папка, куда Next.js собирает проект (если используется static export)
[build]
  command = "npm install && npm run build"
  publish = "out"  # Папка для публикации
